### ISSUE TITLE
Add a LICENSE file to the repository.

### ISSUE THREAD

**Issue by JROB774** [jakebesworth/Simple-SDL2-Audio#5]
It would be nice to have a LICENSE file in the root of the repo to easily see what LICENSE this library is under instead of having to look into the source files.

**Comment by jakebesworth** [comment]
That's a good point, there's an MR up I think that solves this, should be released at some point.

**Comment by jakebesworth** [comment]
Going to close this as it's being added in https://github.com/jakebesworth/Simple-SDL2-Audio/pull/4
