### ISSUE TITLE
line 256: warning: ‘%s’ directive argument is null [-Wformat-overflow=]

### ISSUE THREAD

**Issue by jmgk77** [jakebesworth/Simple-SDL2-Audio#8]
A minor fix,

In line 256, we check for null string, and if its, we try to print the it! It should be:
```
        fprintf(stderr, "[%s: %d]Warning: filename NULL\n", __FILE__, __LINE__);
```
to avoid `warning: ‘%s’ directive argument is null [-Wformat-overflow=]`

**Comment by jakebesworth** [comment]
Are you using C or C++? What compiler are you using?

**Comment by jmgk77** [comment]
i'm using gcc c, from ps3toolchain

but my point is that this line is only reachable is `filename` is null, so there's no point in passing it to `fprintf()`

**Comment by jakebesworth** [comment]
Good point, I'll make a fix for this

**Comment by jakebesworth** [comment]
Fixed
